### ISSUE TITLE
Travel Site

### ISSUE THREAD

**Issue by steven-king** [steven-king/mj487#3]
Post a link to your site here:

**Comment by steven-king** [comment]
http://steventking.com

**Comment by elisabeth-parker** [comment]
http://elisabethparker.net/static/mj487/brisbane/

**Comment by RPappalardo** [comment]
https://rpappalardo.github.io/mj487-andorra/

**Comment by steven-king** [comment]
Looking good! It is nice when you turn it in early so others can see your work!

**Comment by DiandraDwyer** [comment]
It's still a work in progress, but I wanted to go ahead and share the link:
http://diandradwyer.com/mj487/index.html

**Comment by jmwerden** [comment]
http://jeremywerden.com/mj487-egypt/

**Comment by steven-king** [comment]
@jmwerden don't forget to have links to other sites. Needs some kind of navigation.

**Comment by andrea-3000** [comment]
http://andrea-gonzales.com/mj487/norway/

**Comment by alexgorry** [comment]
http://alexgorry.com/MJ487/Canada/canada.html

**Comment by jackmolloy** [comment]
http://jackmolloydesign.com/mj487/chile/

**Comment by carobax** [comment]
http://carolinebaxendale.com/mj487/miami

**Comment by hayleyscialdone** [comment]
http://hayleyscialdone.com/mj487/Copenhagen/learn-bootstrap/index.html

not sure why my css is showing up but hoping to clear that up at the beginning of class! It is working locally but not when I put it on the server! I included a screenshot of what it should look like. 

![screen shot 2017-08-28 at 10 11 07 pm](https://user-images.githubusercontent.com/31298427/29801561-4186cbf4-8c3e-11e7-8411-26040320eefb.png)

**Comment by pandringa** [comment]
https://andrin.ga/mj487/skye

**Comment by xuejinT** [comment]
http://www.tanxuejin.com/mj487/japan/index.html

**Comment by averyhw** [comment]
http://averyhwilliams.com/mj487/london/

**Comment by sabsc** [comment]
http://mejo487.sabcheung.com/mj487/wales/

**Comment by connjin** [comment]
http://www.conniehanzhangjin.com/mj487/hong-kong/

**Comment by MichaelMcGowan** [comment]
http://michaelmcgowan487.com/mj487/new-zealand

**Comment by peytonchance** [comment]
http://peytonchance.com/mj487/quito/

**Comment by mailaw** [comment]
http://mailiislaw.com/mj487/malaysia/

**Comment by mbmouat** [comment]
maggiemouat.com/mj487/peru

**Comment by Gabriella-Bulgarelli** [comment]
http://gabriellabulgarelli.xyz/mj487/dubrovnik/

Locally my site seems to parse correctly, but once I put it on the server things start to work/look incorrectly. I haven't been able to figure out why yet, but I'm posting my link. 
![screen shot 2017-08-29 at 10 09 31 am](https://user-images.githubusercontent.com/31249771/29825370-2f4a2b34-8ca2-11e7-8135-da4e66d3b5d6.png)
![screen shot 2017-08-29 at 10 09 19 am](https://user-images.githubusercontent.com/31249771/29825369-2f49024a-8ca2-11e7-8ea7-fcdabbbc273b.png)

**Comment by Gabriella-Bulgarelli** [comment]
i fixed it!!! WOOO

**Comment by steven-king** [comment]
Great job!
